<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HIH-D-16328" ignored="0" name="_设备1_" tests="9" failures="1" timestamp="26 十二月 2018 11:10:38 GMT" time="528.163" errors="0">
  <testcase name="runCase" time="47.786" classname="com.netease.qa.ai.smartauto.runners.Runner0"/>
  <testcase name="runCase" time="57.467" classname="com.netease.qa.ai.smartauto.runners.Runner1">
    <failure type="java.lang.AssertionError" message="执行失败或程序异常：存在删除。截图及报告：http://smartauto.hz.netease.com/report/casereport?case_id=76919&amp;amp;device_id=3901">
      <![CDATA[java.lang.AssertionError: 执行失败或程序异常：存在删除。截图及报告：http://smartauto.hz.netease.com/report/casereport?case_id=76919&device_id=3901
at com.netease.qa.ai.smartauto.runners.Runner1.runCase(Runner1.java:31)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- runCase -->
  <testcase name="runCase" time="45.663" classname="com.netease.qa.ai.smartauto.runners.Runner2"/>
  <testcase name="runCase" time="73.257" classname="com.netease.qa.ai.smartauto.runners.Runner3"/>
  <testcase name="runCase" time="44.545" classname="com.netease.qa.ai.smartauto.runners.Runner4"/>
  <testcase name="runCase" time="78.083" classname="com.netease.qa.ai.smartauto.runners.Runner5"/>
  <testcase name="runCase" time="51.267" classname="com.netease.qa.ai.smartauto.runners.Runner6"/>
  <testcase name="runCase" time="106.278" classname="com.netease.qa.ai.smartauto.runners.Runner7"/>
  <testcase name="runCase" time="23.752" classname="com.netease.qa.ai.smartauto.runners.Runner8"/>
</testsuite> <!-- _设备1_ -->
